### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Braeders** [EternalFlame06/WarpUtils-Issues#12]
### Bug Description

Hello, i found this mod on modrinth and decided to use it on my server, the hosting service i use is host havoc, when i put it into my mods folder, the server kept crashing.

### Reproduction Steps

Putting the WarpUtils .jar folder into the mods folder

### Log File

idk what to put here

**Comment by EternalFlame06** [comment]
Could you provide me with the crashreport. It should be in the crashreports folder on your server.

**Comment by Braeders** [comment]
Hello, I fixed it, i don’t think it is in the modrinth description or not, but I had to download another mod for this one to work, it’s working now,

**Comment by EternalFlame06** [comment]
Yes the library mod is not in the description. It is usually displayed under versions when you click on one of them.

But there is a bug (from another bug report) that currently causes crashes when the duration of a tpa runs out. I am not sure if this recommendation circumvents the bug because I am currently unable to test it, but try to set the tpa duration to 0 so the duration is infinite.

**Comment by EternalFlame06** [comment]
It seems like the bug existed in version 0.3.0 and not in the newest version. So the tpa duration can be set to any value again.
